**Notebook desenvolvido para o estudo sobre os fundamentos do Tensorflow.**

### Introdução a tensores

Funções e aplicações básicas de tensores utilizando o tensorflow.

In [ ]:
#Import Tensorflow
import tensorflow as tf
print (tf.__version__)

2.5.0


In [ ]:
#Criando tensores com a função tf.constant()
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
#Verificar o número de dimensões do tensor (ndim significa número de dimensões)
scalar.ndim

0

In [ ]:
#Criar um vetor
vetor = tf.constant ([2, 3, 4])
vetor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
#Checar a dimensão do vetor
vetor.ndim

1

In [ ]:
#Criando uma matriz
matriz = tf.constant([[1, 2], [3, 4], [5, 6]])
matriz

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
#Criando outra matriz
outra_matriz = tf.constant([[10., 7.], [3., 2.], [8.,9.]], dtype=tf.float16)  #Dtype é o tipo do dado. No caso, float16 significa que ele tem uma precisão 
                                                                              #de 16 bits.
outra_matriz

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#Vamos criar um Tensor
tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [ ]:
tensor.ndim #Verifica a dimensão desse "tensor". É considerado tensor quando se há mais de duas dimensões.

3

In [ ]:
#Criando tensores com tf.Variable
tensor_mutavel = tf.Variable([10, 7])
tensor_imutavel = tf.constant([10,7])
tensor_mutavel, tensor_imutavel

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Tentando com .assign()
tensor_mutavel[0].assign(7)
tensor_mutavel

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Tensores aleatórios

Em alguns casos, principalmente quando se está fazendo o treinamento inicial do seu algoritmo de machine learning, é interessante que se inicie o treinamento com valores randômicos, para que a partir dele sejam feitas alterações baseadas no aprendizado.

In [ ]:
#Criando tensores aleatórios
random_1 = tf.random.Generator.from_seed(42) # Seta a "seed" para reprodutividade
random_1 = random_1.normal(shape=(3, 2)) # Cria um tensor em uma distribuição normal
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# São iguais?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Criando dois tensores aleatórios (e diferentes)
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Eles são iguais?
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# Embaralhando um tensor 
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Produz diferentes resultados todas as vezes
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Embaralhar na mesma ordem toda vez usando o paramêtro "seed" (Não é verdadeiramente a mesma ordem)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Embaralha na mesma ordem toda vez

# Global Seed
tf.random.set_seed(42)

# Operation Seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### Outros jeitos de se criar tensores

Outras formas de se criar tensores utilizando funções do tensorflow.

In [ ]:
# Cria um tensor de um
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Criar um tensor de zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Você também pode transformar arrays NumPy em tensores.

Lembre-se, a principal diferença entre os arrays NumPy e os tensores é que os tensores podem rodar na GPU para realizar cálculos númericos. 

**Note:** Uma matriz ou tensor é comumente criando com letra maiúscula enquanto um vetor com minúscula.


In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Cria um array NumPy entre 1 e 25.
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # nota: o tamanho total (2*4*3) tem que ser igual ao número de elementos no array.
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

# Obtendo informações dos tensores



Haverão tempos em que você irá necessitar de diferentes tipos de informações de seus tensores, em particular, você precisa saber os seguintes:

* **Forma:** O tamanho (número de elementos) de cada dimensão do tensor.
* **Rank:** O número de dimensões do tensor. Um "scalar" é rank 0, um vetor é rank 1, uma matriz é rank 2, um tensor é rank n.
* **Eixo ou Dimensão:** Uma dimensão em particular do tensor.
* **Tamanho:** O número total de itens no tensor.



In [ ]:
# Cria um tensor rank 4 (4 dimensões)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Retorna vários atributos de um tensor
print("Tipo de data de cada elemento:", rank_4_tensor.dtype)
print("Número de dimensões (rank):", rank_4_tensor.ndim)
print("Forma do tensor:", rank_4_tensor.shape)
print("Elementos no eixo o do tensor:", rank_4_tensor.shape[0])
print("Elementos no último eixo do tensor:", rank_4_tensor.shape[-1])
print("Número total de elementos:", tf.size(rank_4_tensor).numpy()) # .numpy() converte para um array Numpy

Tipo de data de cada elemento: <dtype: 'float32'>
Número de dimensões (rank): 4
Forma do tensor: (2, 3, 4, 5)
Elementos no eixo o do tensor: 2
Elementos no último eixo do tensor: 5
Número total de elementos: 120


### Indexando tensores 

Tensores podem ser indexados assim como listas em Python.

In [ ]:
uma_lista = [1, 2, 3 , 4]
uma_lista[:2]

[1, 2]

In [ ]:
# Retorna os primeiros 2 itens de cada dimensão
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Retorna o primeiro elemento de cada dimensão exceto pelo final
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Cria um tensor rank 2 (2 dimensões)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
uma_lista, uma_lista[-1] #Ultimo item da lista em Python

([1, 2, 3, 4], 4)

In [ ]:
# Retorna o último item de cada "rodada"
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Adiciona uma dimensão extra (no final)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # em Python "..." significa "todas as dimensões antes de"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [2]],
 
        [[3],
         [4]]], dtype=int32)>)

In [ ]:
#Uma Alternativa para o modo acima é utilizar esta função
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" significa último eixo

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0 ) #Expande o eixo 0

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Manipulando tensores (operações em tensores)

**Operações Basicas**

`+`, `-`, `*`, `/`

In [ ]:
# Todas essas operações são feitas por elemento, o que significa que ele vai fazer a operação desejada percorrendo cada elemento do tensor
# Você pode adicionar valores a um tensor usando a operação de soma
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# O tensor original não é modificado
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Multiplicação
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Subtração
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
# Utilizando uma função do tensorflow equivalente a multiplicação
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

**Multiplicação de Matrizes**

Em machine learning, multiplicação de matrizes é uma das operações básicas mais comuns.

[Multiplicação de Matrizes](http://matrixmultiplication.xyz/)

Existem duas regras que nossas matrizes ou tensores precisam ter se nos formos as multiplicar:

1. As dimensões interiores precisam ser iguais.
2. A matriz resultante tem o tamanho das dimensões exteriores.

In [ ]:
#Multiplicação de matrizes no tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
# O tensor original
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
#Multiplicação por elemento, por isso o valor é diferente.
tensor * tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
#Multiplicação de matrizes com o operador "@" do Python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
#A Multiplicação de matrizes funciona pois os dois tensores tem dimensões iguais
tensor.shape

TensorShape([2, 2])

In [ ]:
#Criando um tensor com as dimensões (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#Criando outro tensor com dimensões (3, 2)
Y = tf.constant([[7, 8],
                [9, 10],
                [11, 12]])


X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Multiplicando tensores com a mesma forma
X @ Y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [ ]:
#O y original
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
#Mudando as dimensões de Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Multiplicando o X pelo Y modificado
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Verificando as dimensões caso modificassemos o X no lugar do Y
tf.reshape(X, shape=(2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
# Multiplicando as matrizes, mas dessa vez modificando as dimensões de X
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Podemos fazer o mesmo com a função transpose
X, tf.transpose(X), tf.reshape (X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**Produto Escalar**

Multiplicação de matrizes também é referida como o produto escalar. 

Você pode fazer multiplicação de matrizes utilizando:

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
# Mostra os tensores X e Y
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Fazer o produto escalar entre X e Y (Requer que X e Y sejam modificados)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Normalmente, quando você estiver realizando operações de multiplicação entre dois tensores e uma das dimensões não está alinhada, você vai usar a função transpose (ao invés da reshape) para satisfazer as regras de multiplicação de matrizes.

### Modificando o tipo de dado de um tensor

In [ ]:
# Criando um tensor com o valor padrão
B = tf.constant([1.7, 7.1 ])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.1], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([1, 7])
C.dtype

tf.int32

In [ ]:
# Mudar, por exemplo, de float32 para float16 (Reduzir a precisão)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.1], dtype=float16)>,
 tf.float16)

### Agregando tensores

Agregassão de tensores = Condensar multiplos valores em uma porção menor de valores.

In [ ]:
# Encontrar o valor absoluto
E = tf.constant([-5, -3])
tf.abs(E)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 3], dtype=int32)>

Diferentes formas de agregação:
* `Mínimo`
* `Máximo`
* `Média`
* `Soma`

In [ ]:
# Criando um tensor randômico com valores entre 0 e 100 de tamanho 50
F = tf.constant(np.random.randint(0, 100, size=50))  #"np.random.randint" é uma função da biblioteca numpy para criar arrays randômicos
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([16, 79, 25,  0,  1, 48, 89, 27, 34, 86, 61,  8, 25, 58, 40, 12, 29,
       80, 94,  8, 79,  4,  8, 75, 37, 56, 76, 97, 26, 24, 69, 37, 14, 71,
       84, 25, 44, 96, 40,  7,  5, 30, 52, 34, 79, 61, 50, 65, 95, 18])>

In [ ]:
# Encontrar o mínimo
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Encontrar o máximo
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# Encontrar a média
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
# Encontrar a soma
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2278>

In [ ]:
# Encontrar a variância do nosso tensor
tf.math.reduce_variance(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=881.2064>

In [ ]:
# Encontrar o desvio padrão (Os valores precisam ser do tipo float)
tf.math.reduce_std(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.685122>

### Encontrar a posição máxima e mínima de um tensor



In [ ]:
# Criando um novo tensor para achar a posição do valor máximo e mínimo
tf.random.set_seed(42)
T = tf.random.uniform(shape=[50])
T

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Encontrando a posição do valor máximo do tensor
tf.argmax(T)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [ ]:
# Pegar o valor máximo pelo index
T[tf.argmax(T)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99493325>

In [ ]:
# Encontrar o valor máximo
tf.reduce_max(T)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99493325>

In [ ]:
# Encontrar a posição do valor mínimo
tf.argmin(T)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [ ]:
# Encontrar o valor mínimo pelo index
T[tf.argmin(T)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.028757453>

In [ ]:
# Encontrar o valor mínimo
tf.reduce_min(T)

<tf.Tensor: shape=(), dtype=float32, numpy=0.028757453>